include: package:blackfoot_flutter_lint/blackfoot_flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    prefer_expression_function_bodies: true
    prefer_const_constructors: true
    public_member_api_docs: false
    use_build_context_synchronously: true
