name: HyperTools
description: Collaborer en toute simplicité.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  bloc: ^8.1.2
  provider: ^6.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_black.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo_black.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo_black.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo_black.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
