name: hyper_tools
description: Collaborer en toute simplicité.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  flutter_boxicons: ^3.0.0
  flutter_hooks: ^0.20.3
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.19.0
  provider: ^6.1.1
  shimmer: ^3.0.0

dev_dependencies:
  blackfoot_flutter_lint: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_black.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo_black.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo_black.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo_black.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
