// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEOaK6_9vgEi6t8CoNiqHolJXc_AtKNHU',
    appId: '1:288425956198:web:f4b3cd66a063c83aeb2ea7',
    messagingSenderId: '288425956198',
    projectId: 'hypertools-87410',
    authDomain: 'hypertools-87410.firebaseapp.com',
    storageBucket: 'hypertools-87410.appspot.com',
    measurementId: 'G-SM7RMV0RH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8v1YRrjIC_HhazY--g8EhTQBLFUr6ix0',
    appId: '1:288425956198:android:d585cc156abf5beaeb2ea7',
    messagingSenderId: '288425956198',
    projectId: 'hypertools-87410',
    storageBucket: 'hypertools-87410.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbvA8cV2d2JCUzNCVJrM4XeMKAC0-fD_4',
    appId: '1:288425956198:ios:07798ad353ad44c9eb2ea7',
    messagingSenderId: '288425956198',
    projectId: 'hypertools-87410',
    storageBucket: 'hypertools-87410.appspot.com',
    iosBundleId: 'com.example.pld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbvA8cV2d2JCUzNCVJrM4XeMKAC0-fD_4',
    appId: '1:288425956198:ios:42107f1b37030da2eb2ea7',
    messagingSenderId: '288425956198',
    projectId: 'hypertools-87410',
    storageBucket: 'hypertools-87410.appspot.com',
    iosBundleId: 'com.example.pld.RunnerTests',
  );
}
